import Head from 'next/head'
import Header from '../component/Header'
import Navbar from '../component/Navbar'
import Result from '../component/Result'
import request from '../utils/request'

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>React Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png" />
      </Head>

      {/* header */}
      <Header />

      {/* navbar */}
      <Navbar />

      {/* results */}
      <Result results={results}/>
    </div>
  )
}


  export async function getServerSideProps(context) {
    const {genre} = context.query
    const {value} = context.query

    // Fetch data from external API
    if(value) {
      const requests = await fetch(`https://api.themoviedb.org/3/${request.fetchSearchMovies.url}${value}`).then(res => res.json())
      return { 
      props: 
      { 
        results: requests.results 
      } 
    }
    }
      
    const requests = await fetch(`https://api.themoviedb.org/3/${request[genre]?.url || request.fetchActionMovies.url}`).then( res => res.json())
    // Pass data to the page via props
    return { 
      props: 
      { 
        results: requests.results 
      } 
    }
  }
  

