import Head from 'next/head'
import Header from '../component/Header'
import Navbar from '../component/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png" />
      </Head>

      {/* header */}
      <Header />

      {/* navbar */}
      <Navbar />
    </div>
  )
}
